services:
  redis:
    image: redis/redis-stack:7.2.0-v6
    ports:
      - 6379:6379 # redis server
      - 8001:8001 # redis insight
#    environment:
#      REDIS_ARGS: --requirepass supersecure
    volumes:
        - redisearch-data:/data

volumes:
  redisearch-data:
