version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      - image: redis
    steps:
      # Install PHP Extensions
      - run: sudo pecl install redis
      - run: 'echo -e "memory_limit=-1\n\n[Redis]\nextension=redis.so" | sudo tee /usr/local/etc/php/php.ini > /dev/null'
      - run: "php -r 'foreach (get_loaded_extensions() as $extension) echo \"$extension: \" . phpversion($extension) . PHP_EOL;'"
      # Checkout code
      - checkout
      # Install Dependencies
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
            - ~/.composer/cache
      # Run Tests
      - run: composer lint
      - run: vendor/bin/phpunit
