version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      - image: redis
    steps:
      # Install PHP Extensions
      - run: pecl install redis-4.2.0
      - run: docker-php-ext-enable redis
      # Checkout code
      - checkout
      # Install Dependencies
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
            - ~/.composer/cache
      # Run Tests
      - run: vendor/bin/phpunit
